# Generated by Django 5.0.3 on 2024-03-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='layout',
            field=models.ImageField(default='default.jpg', help_text='Upload your layout here.', upload_to='layouts'),
        ),
        migrations.AlterField(
            model_name='job',
            name='egress_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='egress_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='ingress_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='ingress_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
