# Generated by Django 5.0.3 on 2024-03-21 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_layout_alter_job_egress_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cluster_booth_count_2x2',
            field=models.CharField(choices=[('0', '0'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12')], default='0', max_length=2, verbose_name='Cluster Booth Count: 2 x 2 meters'),
        ),
        migrations.AddField(
            model_name='job',
            name='cluster_booth_count_2x3',
            field=models.CharField(choices=[('0', '0'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12')], default='0', max_length=2, verbose_name='Cluster Booth Count: 2 x 3 meters'),
        ),
        migrations.AddField(
            model_name='job',
            name='cluster_booth_count_3x3',
            field=models.CharField(choices=[('0', '0'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12')], default='0', max_length=2, verbose_name='Cluster Booth Count: 3 x 3 meters'),
        ),
        migrations.AddField(
            model_name='job',
            name='cluster_booth_count_3x4',
            field=models.CharField(choices=[('0', '0'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12')], default='0', max_length=2, verbose_name='Cluster Booth Count: 3 x 4 meters'),
        ),
        migrations.AddField(
            model_name='job',
            name='cluster_booth_count_4x4',
            field=models.CharField(choices=[('0', '0'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12')], default='0', max_length=2, verbose_name='Cluster Booth Count: 4 x 4 meters'),
        ),
        migrations.AddField(
            model_name='job',
            name='cluster_total_count_2x2',
            field=models.IntegerField(default=0, verbose_name='Cluster Total Count: 2 x 2 meters'),
        ),
        migrations.AddField(
            model_name='job',
            name='cluster_total_count_2x3',
            field=models.IntegerField(default=0, verbose_name='Cluster Total Count: 2 x 3 meters'),
        ),
        migrations.AddField(
            model_name='job',
            name='cluster_total_count_3x3',
            field=models.IntegerField(default=0, verbose_name='Cluster Total Count: 3 x 3 meters'),
        ),
        migrations.AddField(
            model_name='job',
            name='cluster_total_count_3x4',
            field=models.IntegerField(default=0, verbose_name='Cluster Total Count: 3 x 4 meters'),
        ),
        migrations.AddField(
            model_name='job',
            name='cluster_total_count_4x4',
            field=models.IntegerField(default=0, verbose_name='Cluster Total Count: 4 x 4 meters'),
        ),
        migrations.AddField(
            model_name='job',
            name='contingency',
            field=models.IntegerField(default=0, help_text='E.g. Enter 10 for 10%'),
        ),
        migrations.AddField(
            model_name='job',
            name='perimeter_booth_count_2x2',
            field=models.CharField(choices=[('0', '0'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='0', max_length=2, verbose_name='Perimeter Booth Count: 2 x 2 meters'),
        ),
        migrations.AddField(
            model_name='job',
            name='perimeter_booth_count_2x3',
            field=models.CharField(choices=[('0', '0'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='0', max_length=2, verbose_name='Perimeter Booth Count: 2 x 3 meters'),
        ),
        migrations.AddField(
            model_name='job',
            name='perimeter_booth_count_3x3',
            field=models.CharField(choices=[('0', '0'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='0', max_length=2, verbose_name='Perimeter Booth Count: 3 x 3 meters'),
        ),
        migrations.AddField(
            model_name='job',
            name='perimeter_total_count_2x2',
            field=models.IntegerField(default=0, verbose_name='Perimeter Total Count: 2 x 2 meters'),
        ),
        migrations.AddField(
            model_name='job',
            name='perimeter_total_count_2x3',
            field=models.IntegerField(default=0, verbose_name='Perimeter Total Count: 2 x 3 meters'),
        ),
        migrations.AddField(
            model_name='job',
            name='perimeter_total_count_3x3',
            field=models.IntegerField(default=0, verbose_name='Perimeter Total Count: 3 x 3 meters'),
        ),
        migrations.CreateModel(
            name='BomGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.IntegerField(editable=False)),
                ('panel', models.IntegerField(editable=False)),
                ('beam', models.IntegerField(editable=False)),
                ('facia_length', models.IntegerField(editable=False)),
                ('facia_width', models.IntegerField(editable=False)),
                ('corner_length_beam', models.IntegerField(editable=False)),
                ('corner_width_beam', models.IntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='jobs.job')),
            ],
        ),
    ]
