# Generated by Django 5.0.3 on 2024-03-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_cluster_booth_count_2x2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomgeneration',
            options={'verbose_name': 'BOM Generation', 'verbose_name_plural': 'BOM Generations'},
        ),
        migrations.RemoveField(
            model_name='bomgeneration',
            name='beam',
        ),
        migrations.RemoveField(
            model_name='bomgeneration',
            name='corner_length_beam',
        ),
        migrations.RemoveField(
            model_name='bomgeneration',
            name='corner_width_beam',
        ),
        migrations.RemoveField(
            model_name='bomgeneration',
            name='facia_length',
        ),
        migrations.RemoveField(
            model_name='bomgeneration',
            name='facia_width',
        ),
        migrations.RemoveField(
            model_name='bomgeneration',
            name='panel',
        ),
        migrations.RemoveField(
            model_name='bomgeneration',
            name='post',
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_beam_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Beam 2 x 2'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_beam_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Beam 2 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_beam_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Beam 3 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_beam_3x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Beam 3 x 4'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_beam_4x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Beam 4 x 4'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_corner_length_beam_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Corner Length Beam 2 x 2'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_corner_length_beam_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Corner Length Beam 2 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_corner_length_beam_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Corner Length Beam 3 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_corner_length_beam_3x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Corner Length Beam 3 x 4'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_corner_length_beam_4x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Corner Length Beam 4 x 4'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_corner_width_beam_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Corner Width Beam 2 x 2'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_corner_width_beam_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Corner Width Beam 2 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_corner_width_beam_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Corner Width Beam 3 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_corner_width_beam_3x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Corner Width Beam 3 x 4'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_corner_width_beam_4x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Corner Width Beam 4 x 4'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_facia_length_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Facia Length 2 x 2'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_facia_length_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Facia Length 2 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_facia_length_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Facia Length 3 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_facia_length_3x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Facia Length 3 x 4'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_facia_length_4x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Facia Length 4 x 4'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_facia_width_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Facia Width 2 x 2'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_facia_width_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Facia Width 2 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_facia_width_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Facia Width 3 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_facia_width_3x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Facia Width 3 x 4'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_facia_width_4x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Facia Width 4 x 4'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_panel_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Panel 2 x 2'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_panel_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Panel 2 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_panel_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Panel 3 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_panel_3x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Panel 3 x 4'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_panel_4x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Panel 4 x 4'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_post_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Post 2 x 2'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_post_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Post 2 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_post_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Post 3 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_post_3x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Post 3 x 4'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='cluster_post_4x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster Post 4 x 4'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_beam_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Beam 2 x 2'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_beam_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Beam 2 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_beam_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Beam 3 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_corner_length_beam_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Corner Length Beam 2 x 2'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_corner_length_beam_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Corner Length Beam 2 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_corner_length_beam_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Corner Length Beam 3 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_corner_width_beam_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Corner Width Beam 2 x 2'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_corner_width_beam_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Corner Width Beam 2 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_corner_width_beam_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Corner Width Beam 3 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_facia_length_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Facia Length 2 x 2'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_facia_length_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Facia Length 2 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_facia_length_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Facia Length 3 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_facia_width_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Facia Width 2 x 2'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_facia_width_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Facia Width 2 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_facia_width_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Facia Width 3 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_panel_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Panel 2 x 2'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_panel_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Panel 2 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_panel_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Panel 3 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_post_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Post 2 x 2'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_post_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Post 2 x 3'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='perimeter_post_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Perimeter Post 3 x 3'),
        ),
        migrations.AlterField(
            model_name='job',
            name='cluster_booth_count_2x2',
            field=models.CharField(choices=[('0', '0'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12')], default='0', max_length=2, verbose_name='Booth Count: 2 x 2 meters'),
        ),
        migrations.AlterField(
            model_name='job',
            name='cluster_booth_count_2x3',
            field=models.CharField(choices=[('0', '0'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12')], default='0', max_length=2, verbose_name='Booth Count: 2 x 3 meters'),
        ),
        migrations.AlterField(
            model_name='job',
            name='cluster_booth_count_3x3',
            field=models.CharField(choices=[('0', '0'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12')], default='0', max_length=2, verbose_name='Booth Count: 3 x 3 meters'),
        ),
        migrations.AlterField(
            model_name='job',
            name='cluster_booth_count_3x4',
            field=models.CharField(choices=[('0', '0'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12')], default='0', max_length=2, verbose_name='Booth Count: 3 x 4 meters'),
        ),
        migrations.AlterField(
            model_name='job',
            name='cluster_booth_count_4x4',
            field=models.CharField(choices=[('0', '0'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12')], default='0', max_length=2, verbose_name='Booth Count: 4 x 4 meters'),
        ),
        migrations.AlterField(
            model_name='job',
            name='cluster_total_count_2x2',
            field=models.IntegerField(default=0, verbose_name='Total Count: 2 x 2 meters'),
        ),
        migrations.AlterField(
            model_name='job',
            name='cluster_total_count_2x3',
            field=models.IntegerField(default=0, verbose_name='Total Count: 2 x 3 meters'),
        ),
        migrations.AlterField(
            model_name='job',
            name='cluster_total_count_3x3',
            field=models.IntegerField(default=0, verbose_name='Total Count: 3 x 3 meters'),
        ),
        migrations.AlterField(
            model_name='job',
            name='cluster_total_count_3x4',
            field=models.IntegerField(default=0, verbose_name='Total Count: 3 x 4 meters'),
        ),
        migrations.AlterField(
            model_name='job',
            name='cluster_total_count_4x4',
            field=models.IntegerField(default=0, verbose_name='Total Count: 4 x 4 meters'),
        ),
        migrations.AlterField(
            model_name='job',
            name='perimeter_booth_count_2x2',
            field=models.CharField(choices=[('0', '0'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='0', max_length=2, verbose_name='Booth Count: 2 x 2 meters'),
        ),
        migrations.AlterField(
            model_name='job',
            name='perimeter_booth_count_2x3',
            field=models.CharField(choices=[('0', '0'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='0', max_length=2, verbose_name='Booth Count: 2 x 3 meters'),
        ),
        migrations.AlterField(
            model_name='job',
            name='perimeter_booth_count_3x3',
            field=models.CharField(choices=[('0', '0'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='0', max_length=2, verbose_name='Booth Count: 3 x 3 meters'),
        ),
        migrations.AlterField(
            model_name='job',
            name='perimeter_total_count_2x2',
            field=models.IntegerField(default=0, verbose_name='Total Count: 2 x 2 meters'),
        ),
        migrations.AlterField(
            model_name='job',
            name='perimeter_total_count_2x3',
            field=models.IntegerField(default=0, verbose_name='Total Count: 2 x 3 meters'),
        ),
        migrations.AlterField(
            model_name='job',
            name='perimeter_total_count_3x3',
            field=models.IntegerField(default=0, verbose_name='Total Count: 3 x 3 meters'),
        ),
    ]
