# Generated by Django 5.0.3 on 2024-03-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_bomgeneration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomgeneration',
            name='total_beams',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total Beams'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='total_corner_length_beams',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total Corner Length Beams'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='total_corner_width_beams',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total Corner Width Beams'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='total_facia_lengths',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total Facia Lengths'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='total_facia_widths',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total Facia Widths'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='total_panels',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total Panels'),
        ),
        migrations.AddField(
            model_name='bomgeneration',
            name='total_posts',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total Posts'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_beam_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 2'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_beam_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_beam_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_beam_3x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 4'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_beam_4x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='4 x 4'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_corner_length_beam_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 2'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_corner_length_beam_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_corner_length_beam_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_corner_length_beam_3x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 4'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_corner_length_beam_4x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='4 x 4'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_corner_width_beam_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 2'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_corner_width_beam_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_corner_width_beam_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_corner_width_beam_3x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 4'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_corner_width_beam_4x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='4 x 4'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_facia_length_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 2'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_facia_length_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_facia_length_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_facia_length_3x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 4'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_facia_length_4x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='4 x 4'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_facia_width_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 2'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_facia_width_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_facia_width_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_facia_width_3x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 4'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_facia_width_4x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='4 x 4'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_panel_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 2'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_panel_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_panel_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_panel_3x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 4'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_panel_4x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='4 x 4'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_post_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 2'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_post_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_post_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_post_3x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 4'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='cluster_post_4x4',
            field=models.IntegerField(default=0, editable=False, verbose_name='4 x 4'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_beam_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 2'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_beam_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_beam_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_corner_length_beam_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 2'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_corner_length_beam_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_corner_length_beam_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_corner_width_beam_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 2'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_corner_width_beam_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_corner_width_beam_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_facia_length_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 2'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_facia_length_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_facia_length_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_facia_width_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 2'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_facia_width_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_facia_width_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_panel_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 2'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_panel_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_panel_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_post_2x2',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 2'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_post_2x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='2 x 3'),
        ),
        migrations.AlterField(
            model_name='bomgeneration',
            name='perimeter_post_3x3',
            field=models.IntegerField(default=0, editable=False, verbose_name='3 x 3'),
        ),
    ]
