# Generated by Django 5.0.3 on 2024-03-20 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(help_text='Password must contain one letter, one digit, and must be at least 8 characters', max_length=128, validators=[django.core.validators.RegexValidator(message='Password must contain one letter, one digit, and must be at least 8 characters', regex='^(?=.*[a-zA-Z])(?=.*\\d).{8,}.*$')]),
        ),
    ]
