# Generated by Django 5.0.3 on 2024-03-21 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options_alter_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(help_text='Password must contain at least one letter, and must be at least 8 characters', max_length=128, validators=[django.core.validators.RegexValidator(message='Password must contain at least one letter, and must be at least 8 characters', regex='^(?=.*[a-zA-Z]).{8,}.*$')]),
        ),
    ]
