# Generated by Django 5.0.3 on 2024-03-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_type', models.CharField(choices=[('Cluster', 'Cluster'), ('Perimeter', 'Perimeter')], max_length=255)),
                ('name', models.CharField(choices=[('Cluster 2x2 meters', 'Cluster 2x2 meters'), ('Cluster 2x3 meters', 'Cluster 2x3 meters'), ('Cluster 3x3 meters', 'Cluster 3x3 meters'), ('Cluster 3x4 meters', 'Cluster 3x4 meters'), ('Cluster 4x4 meters', 'Cluster 4x4 meters'), ('Perimeter 2x2 meters', 'Perimeter 2x2 meters'), ('Perimeter 2x3 meters', 'Perimeter 2x3 meters'), ('Perimeter 3x3 meters', 'Perimeter 3x3 meters')], max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('setup_type', 'name')},
            },
        ),
    ]
